keycloak:
  realm: Pfe-Star
  domain: localhost:8081
  adminClientId: admin-cli
  adminClientSecret: sFdkg97Y1pi695hdMqXTRsdy3iyghVfp
  client: authenticationClientId
  urls:
    auth: http://${keycloak.domain}

management:
  endpoints:
    web:
      exposure:
        include: '*'
    endpoint:
      health:
        show-details: always

server:
  port: 8082